server:
  port: 8080

spring:
  application:
    name : pos-backend-api
  profiles:
    active: @spring.profiles.active@

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
        # include: health,prometheus,metrics

logging:
  level:
    root: INFO
    web: OFF